app/main/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from flask_babelex import lazy_gettext as _l
from app.security2 import UniqueUserNameRequired

from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, StopValidation, Length


class FormDataRequired(object):
    """
    Validate form for some data
    """
    field_flags = ('required',)

    def __init__(self, message=None):
        if message:
            self.message = message
        else:
            self.message = _l('You must fill in at least one field')

    def __call__(self, form, field):
        is_data = False
        skipped = ['button', 'csrf_token']
        for field_form in form:
            if field_form.id not in skipped and field_form.data:
                is_data = True
        if not is_data:
            raise StopValidation(self.message)


class ProfileForm(FlaskForm):
    username = StringField(_l('Username'), [UniqueUserNameRequired()])
    about = TextAreaField(_l('About'), [Length(0, 255)])
    file = FileField(_l('Add image'), [FileAllowed(['jpg', 'png', 'png'], _l('Images only!'))])
    button = SubmitField(_l('Apply'), [FormDataRequired()])


class AddNewPostForm(FlaskForm):
    title = StringField(_l('Title'), validators=[DataRequired(), Length(1, 50)])
    post = TextAreaField(_l('New post'), validators=[DataRequired()])
    button = SubmitField(_l('Submit'))


class AddCommentForm(FlaskForm):
    comment = TextAreaField(_l('Your comment'), validators=[DataRequired()])
    button = SubmitField(_l('Submit'))

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import views

app/main/views.py
import base64
from datetime import datetime

from flask import render_template, redirect, url_for, abort, request, flash, jsonify, session, current_app
from flask_babelex import get_locale, gettext
from flask_security import current_user, auth_required

from app import db
from app.main import bp
from app.main.forms import AddNewPostForm, AddCommentForm, ProfileForm
from app.main.utils import add_to_db, get_post_hash
from app.models import Post, Comment, User


@bp.route('/language/<language>')
def set_language(language=None):
    session["lang"] = language
    return redirect(request.args["next"])


@bp.before_request
def before_request():
    session["lang"] = str(get_locale())
    if current_user.is_authenticated:
        current_user.last_login_at = datetime.utcnow()
        db.session.commit()


# @bp.route("/")
# @bp.route("/blog")
# @bp.route("/feed")
# def index():
#     paths = {
#         "/": "Post.query.order_by(Post.created_at.desc())",
#         "/blog": "Post.query.filter_by(user_id=current_user.id).order_by(Post.created_at.desc())",
#         "/feed": "current_user.followed_posts()",
#     }
#     print(request.path)
#     posts = eval(paths[request.path])
#     print(post)
#     c_page = request.args.get('page', 1, type=int)
#     page = posts.paginate(c_page, current_app.config["POSTS_PER_PAGE"], False)
#     return render_template("main/index.html", page=page)





@bp.route("/")
def index():
    posts = Post.query.order_by(Post.created_at.desc())
    c_page = request.args.get('page', 1, type=int)
    page = posts.paginate(c_page, current_app.config["POSTS_PER_PAGE"], False)
    return render_template("main/index.html", page=page)


@bp.route("/blog")
@auth_required('token', 'session')
def blog():
    print(request.path)
    posts = Post.query.filter_by(user_id=current_user.id).order_by(Post.created_at.desc())
    c_page = request.args.get('page', 1, type=int)
    page = posts.paginate(c_page, current_app.config["POSTS_PER_PAGE"], False)
    return render_template("main/index.html", page=page)


@bp.route("/feed")
@auth_required('token', 'session')
def feed():
    posts = current_user.followed_posts()
    c_page = request.args.get('page', 1, type=int)
    page = posts.paginate(c_page, current_app.config["POSTS_PER_PAGE"], False)
    return render_template("main/index.html", page=page)


@bp.route("/profile", methods=["POST", "GET"])
@auth_required('token', 'session')
def private_profile():
    profile_form = ProfileForm(obj=current_user)
    if profile_form.validate_on_submit():
        filename = profile_form.file.data
        username = profile_form.username.data
        about = profile_form.about.data
        if filename:
            file = request.files['file'].read()
            current_user.user_avatar = file
        if username:
            current_user.username = username
        current_user.about = about
        try:
            db.session.commit()
            flash(gettext('Changes saved.'), "success")
            return redirect(url_for("main.private_profile"))
        except Exception as err:
            db.session.rollback()
            flash(gettext('Error'), "danger")
            current_app.logger.error(f"sql error: {err.args}")
    return render_template("main/edit_profile.html", form=profile_form)


@bp.route("/profile/<username>")
def profile(username):
    user_obj = User.query.filter_by(username=username).first()
    if user_obj:
        if user_obj.user_avatar:
            avatar = base64.b64encode(user_obj.user_avatar).decode('ascii')
        else:
            avatar = False
        tab = request.args.get("tab", "Posts")
        c_page = request.args.get('page', 1, type=int)
        page = eval(tab[:-1]).query.filter_by(user_id=user_obj.id).paginate(c_page, 8, False)
        params = {"username": username, "tab": tab}
        return render_template("main/public_profile.html", user=user_obj, avatar=avatar, tab=tab,
                               need_extends=True, page=page, params=params)
    else:
        abort(404)


@bp.route("/popover/<username>")
def popover(username):
    user_obj = User.query.filter_by(username=username).first()
    if user_obj:
        if user_obj.user_avatar:
            avatar = base64.b64encode(user_obj.user_avatar).decode('ascii')
        else:
            avatar = False
        return render_template("main/_min_profile.html", user=user_obj, avatar=avatar)
    else:
        abort(404)


@bp.route("/post/<post_hash>", methods=["POST", "GET"])
def post(post_hash):
    getting_post = Post.query.filter_by(hash_name=post_hash)
    comment_form = AddCommentForm()
    if getting_post.count():
        if comment_form.validate_on_submit():
            comment = Comment(body=comment_form.comment.data, post_id=getting_post.first().id,
                              user_id=current_user.id)
            add_to_db(comment)
            return redirect(url_for("main.post", post_hash=post_hash))
        c_page = request.args.get('page', 1, type=int)
        page = getting_post.first().comments.paginate(c_page, current_app.config["COMMENTS_PER_PAGE"], False)
        params = {"post_hash": post_hash}
        return render_template("main/post.html", post=getting_post.first(),
                               add_comment_form=comment_form, page=page, params=params)
    else:
        return abort(404)


@bp.route("/newpost", methods=["POST", "GET"])
@auth_required('token', 'session')
def new_post():
    post_form = AddNewPostForm()
    if post_form.validate_on_submit():
        post = Post(title=post_form.title.data, body=post_form.post.data,
                    user_id=current_user.id, hash_name=get_post_hash())
        add_to_db(post)
        return redirect(url_for("main.blog"))
    return render_template("main/new_post.html", add_post_form=post_form)


@bp.route("/subscriptions")
@auth_required('token', 'session')
def subscriptions():
    return render_template("main/subscriptions.html")


@bp.route("/subscribe")
@auth_required('token', 'session')
def subscribe():
    subscriber = User.query.get(current_user.id)
    recipient = User.query.filter_by(username=request.args["recipient"]).first()
    action = request.args["action"]
    try:
        if action == "append":
            subscriber.follow(recipient)
        elif action == "remove":
            subscriber.unfollow(recipient)
        db.session.commit()
        return jsonify({"good": "ok"})
    except Exception as err:
        current_app.logger.error(f"sql error: {err}")
        return jsonify({"error": "Error"})


@bp.route("/links")
def links():
    links = (
        "https://flask-migrate.readthedocs.io/en/latest/",
        "https://flask-security-too.readthedocs.io/en/stable/index.html")
    return render_template("main/links.html", links=links)

app/templates/main/_articles.html
{% set articles  = {
    _("New post"):{"icon":"bi-plus-lg","href":url_for("main.new_post")},
    _("Profile"): {"icon":"bi-person","href":url_for("main.profile", username=current_user.username)},
    _("Subscriptions"): {"icon":"bi-people-fill","href":url_for("main.subscriptions")},
    _("Exit"):{"icon":"bi-box-arrow-right","href":url_for_security("logout")},} %}


<div class="position-sticky shadow p-3 mb-5 bg-body rounded" style="top: 2rem;">
    {% block personalmenu %}
        {% if current_user.is_authenticated %}
            <div class="p-4">
                <ul class="list-group list-unstyled border-0">
                    {% for key in articles %}
                        <li class="list-group-flush">
                            <a class="link-secondary text-decoration-none" href="{{ articles[key]["href"] }}">
                                <i class={{ articles[key]["icon"] }}> </i>{{ key }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endblock %}
    {% block timeline %}
        <div class="p-4">
            <h4 class="fst-italic">Archives</h4>
            <ol class="list-unstyled mb-0">
                <li><a href="#">March 2021</a></li>
                <li><a href="#">February 2021</a></li>
                <li><a href="#">January 2021</a></li>
                <li><a href="#">December 2020</a></li>
                <li><a href="#">November 2020</a></li>
                <li><a href="#">October 2020</a></li>
                <li><a href="#">September 2020</a></li>
                <li><a href="#">August 2020</a></li>
                <li><a href="#">July 2020</a></li>
                <li><a href="#">June 2020</a></li>
                <li><a href="#">May 2020</a></li>
                <li><a href="#">April 2020</a></li>
            </ol>
        </div>
    {% endblock %}
</div>

app/templates/main/_button.html
{% macro button_subscribe(user, color, friendship) %}
    {% set full_url = url_for("main.subscribe", _external=True) %}
    <button id="friendship" type="button"
            onclick="makeFriendship.call(this,'{{ full_url }}', '{{ user.username }}');"
            class="btn btn-{{ color }} bi {{ friendship }} float-end" value="friends">
    </button>
{% endmacro %}

app/templates/main/_navigation.html
{% set nav = {
  "main.blog": {
    "name": _("My blog"),
    "active": "active",
  },
  "main.feed": {
    "name": _("Feed"),
    "active": "",
  },
  "main.links": {
    "name": _("Links"),
    "active": "",
  }
} %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container-fluid">
        {% set ggg = 123 %}
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Flask{{ _("Blogs") }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                {% if not current_user.is_authenticated %}
                    {% set class_disabled = 'disabled' %}
                    {% set aria_disabled = 'aria-disabled="true"' %}
                {% endif %}
                {% for item in nav %}
                    {% if request.endpoint == item %}
                        {% set nav_active = "active" %}
                    {% else %}
                        {% set nav_active = "" %}
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link {{ nav_active }} {{ class_disabled if item != "links" else "" }}"
                           aria-current="page" {{ aria_disabled if item != "links" else "" }}
                           href="{{ url_for(item) }}">
                            {{ nav[item]["name"] }}
                        </a>
                    </li>
                {% endfor %}
                {% if request.endpoint %}
                    {% set lang = {"ru":"Русский","en":"English"} %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="" id="navbarDarkDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {{ lang[session.get("lang")] }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                            <li><a class="dropdown-item"
                                   href="{{ url_for('main.set_language', language="ru", next=request.url) }}">{{ lang["ru"] }}</a>
                            </li>
                            <li><a class="dropdown-item"
                                   href="{{ url_for('main.set_language', language="en", next=request.url) }}">{{ lang["en"] }}</a>
                            </li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
            {% if current_user.is_anonymous %}
                {% set name_user =  _('Login') %}
                {% set href = url_for_security('login') %}
            {% else %}
                {% set name_user = current_user.username %}
                {% set href = url_for('main.profile', username=name_user) %}
            {% endif %}
            <a class="" href="{{ href }}">
                <button class="btn btn-outline-secondary" type="submit">{{ name_user }}</button>
            </a>
            <form class="d-flex">
                <input class="form-control mx-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">{{ _("Search") }}</button>
            </form>
        </div>
    </div>
</nav>

app/templates/main/_pagenation.html
{% if page.pages > 1 %}
    {% if not params %}{% set params = {} %}{% endif %}
    <div aria-label="Page navigation">
        <ul class="pagination">
            {% if not page.has_prev %}
                <li class="page-item {{ prev }}">
                    <a class="page-link" href="{{ url_for(request.endpoint, page=page.prev_num, **params) }}"
                       aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a></li>
            {% endif %}
            {% for page_num in range(1,page.pages + 1) %}
                {% if page.page - 3 < page_num < page.page + 3 %}
                    <li class="page-item {% if page_num == page.page %}active{% endif %}">
                        <a class="page-link" href="{{ url_for(request.endpoint, page=page_num, **params) }}">
                            {{ page_num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page.has_next %}
                <li class="page-item {{ next }}">
                    <a class="page-link" href="{{ url_for(request.endpoint, page=page.next_num, **params) }}"
                       aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a></li>
            {% endif %}
        </ul>
    </div>
{% endif %}

app/templates/main/_pills.html
{% set pills = {_("Posts"):"Posts",  _("Comments"):"Comments"} %}
<div class="btn-group" role="group" aria-label="conten choise">
    {% for key, item in pills.items() %}
        {% if item == params["tab"] %}
            {% set  class_active = 'btn btn-primary active' %}
        {% else %}
            {% set  class_active = 'btn btn-outline-secondary' %}
        {% endif %}
        {% set temp = params["tab"] %}
        {% set _t = params.update({"tab":item}) %}
        <a href="{{ url_for(request.endpoint, page=1, **params) }}">
            <button type="button" class="{{ class_active }}">{{ key }}</button>
        </a>
        {% set _t = params.update({"tab":temp}) %}
    {% endfor %}
</div>

app/templates/main/_username.html
{% macro build_user(user) %}
    <a class="link-popover" data-bs-toggle="popover"
       href="{{ url_for('main.profile', username=user.username ) }}">{{ user.username }}
    </a>
{% endmacro %}

app/templates/main/base.html
<!doctype html>
<html lang="{{ session['lang'] }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="education project flask/python">
    <title>Flask Дневник</title>
    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="#">
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static',filename='css/navbar-top.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/blog.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/inline_img.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    {% block css %}
    {% endblock %}
    {% block scripts %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        {{ moment.include_moment() }}
        {{ moment.lang(session['lang']) }}
    {% endblock %}
</head>
<body>

{% include "main/_navigation.html" %}

<main class="container">
    <div class="row g-5">
        <section class="col-md-9">
            {% block content %}

            {% endblock %}
        </section>
        <section class="col-md-3">
            {% include "main/_articles.html" %}
        </section>
    </div>
</main>
<script src="{{ url_for('static',filename='js/bootstrap.bundle.min.js') }}"></script>
<footer class="blog-footer">
    {% block footer %}
        <p>
            <a href="#">Back to top</a>
        </p>
    {% endblock %}
</footer>
<script src="{{ url_for("static", filename="js/blog.js") }}"></script>
<script>

</script>
</body>
</html>

app/templates/main/edit_profile.html
{% extends "main/base.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field, render_field_with_errors_without_label %}
{% block content %}
    <div class="container">
        <form class="form-row m-3 w-50" action="{{ url_for('main.private_profile') }}" method="post"
              enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {{ render_field_with_errors(form.username, class="form-control") }}
            {{ render_field_with_errors(form.about, class="form-control") }}
            {{ render_field_with_errors(form.file, class="form-control") }}
            {{ render_field_with_errors_without_label(form.button, class="btn btn-primary") }}
            {% include "security/_messages.html" %}
        </form>
    </div>
{% endblock %}

app/templates/main/index.html
{% extends "main/base.html" %}

{% block content %}
    {% for post in page.items %}
        {% set post_href = url_for("main.post", post_hash=post.hash_name) %}
        <article class="blog-post shadow p-3 mb-5 bg-body rounded"
                 onclick="window.location.href = '{{ post_href }}'">
            <a class="text-decoration-none link-dark" href="{{ post_href }}">
                <h2 class="blog-post-title">{{ post.title }}</h2>
            </a>
            <p class="blog-post-meta">{{ moment(post.created_at).calendar() }}
                {% from "main/_username.html" import build_user %}
                {{ build_user(post.user) }}
            </p>
            <p>{{ post.body }}</p>
            {% set comments_couut = post.comments.all()|length %}
            <p class="blog-post-meta border-2 border-top">
                {{ _("Comments") }}: {{ comments_couut }}</p>
        </article>
    {% endfor %}
    {% include "main/_pagenation.html" %}
{% endblock %}

app/templates/main/links.html
{% extends "main/base.html" %}

{% block content %}
    <div class="p-5">
        <ul class="list-unstyled mb-0">
            {% for link in links %}
                <li><a href="{{ link }}">{{ link }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

app/templates/main/new_post.html
{% extends "main/base.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% block content %}
    <div class="container">
        <h3 class="text-center">{{ _("New post") }}</h3>
        <form class="form-row" action="{{ url_for('main.new_post') }}" method="POST">
            {{ add_post_form.hidden_tag() }}
            {{ render_field_with_errors(add_post_form.title, class="form-control") }}
            {{ render_field_with_errors(add_post_form.post, class="form-control") }}
            {{ render_field(add_post_form.button, class="btn btn-lg btn-primary") }}
        </form>
    </div>
{% endblock %}

app/templates/main/post.html
{% extends "main/base.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% block content %}
    <article class="blog-post">
        <h2 class="blog-post-title">{{ post.title }}</h2>
        <p>{{ post.body }}</p>
        <ul class="list-group">
            {% for comment in page.items %}
                <li class="list-group-item border-0">
                    <p>
                        <img class="inline-img" src="{{ comment.user.avatar() }}">
                        <b class="me-3">
                            {% from "main/_username.html" import build_user %}
                            {{ build_user(comment.user) }}
                        </b>{{ moment(comment.created_at).calendar() }}
                    </p>
                    <p class="border-bottom border-3 mb-2">{{ comment.body }}</p>
                </li>
            {% endfor %}
        </ul>
        {% include "main/_pagenation.html" %}
        {% if current_user.is_authenticated %}
            <form class="form-row" action="" method="POST">
                {{ add_comment_form.hidden_tag() }}
                {{ render_field_with_errors(add_comment_form.comment, class="form-control") }}
                {{ render_field(add_comment_form.button ,class="btn btn-lg btn-primary") }}
            </form>
        {% endif %}
    </article>
{% endblock %}

app/templates/main/public_profile.html
{% extends "main/base.html" %}
{% block content %}
    <div class="row">
        {% block profile_base %}
            {% include "main/_min_profile.html" %}
        {% endblock %}
        {% if need_extends %}
            {% block profile_extend %}
                <div class="container">
                    {% include "main/_pills.html" %}
                    <div class="col-md shadow-primary border-primary">
                        {% if page %}
                            <ul class="list-group"></ul>
                            {% for item in page.items %}
                                <li class="list-group-item border-0">
                                    {% if item.title %}
                                        <a class="link-secondary text-decoration-none"
                                           href="{{ url_for("main.post", post_hash=item.hash_name) }}">
                                        {{ item.title }}
                                    {% else %}
                                        <a class="link-secondary text-decoration-none"
                                           href="{{ url_for("main.post", post_hash=item.post.hash_name) }}">
                                        {{ item.body }}
                                    {% endif %}
                                    </a>
                                </li>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <p></p>
                    {% include "main/_pagenation.html" %}
                </div>
            {% endblock %}
        {% endif %}
    </div>
{% endblock %}

app/templates/main/subscriptions.html
{% extends "main/base.html" %}

{% block content %}
    {% from "main/_button.html" import button_subscribe %}
    <div class="row">
        <div class="col-md">
            <h5 class="text-center fst-italic">{{_("Subscriptions")}}</h5>
            <ul class="list-group">
                {% for user in current_user.followed.all() %}
                    <a class="text-decoration-none" href="{{ url_for("main.profile", username=user.username) }}">
                        <li class="list-group-item">{{ user.username }}</li>
                    </a>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md">
            <h5 class="text-center fst-italic">{{ _("Subscribers") }}</h5>
            {% for user in current_user.followers.all() %}
                <a class="text-decoration-none" href="{{ url_for("main.profile", username=user.username) }}">
                    <li class="list-group-item">{{ user.username }}</li>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}